### ISSUE TITLE
Cannot install Rmath for julia 0.5.0 on Mac OS X

### ISSUE THREAD

**Issue by shreczka** [JuliaLang/Rmath-julia#15]
Hi,
when trying to install Rmath for julia 0.5.0 i get the following error. Could you please help me to install it?

`make -C src
rm -rf libRmath-julia.dylib
gcc   -shared -o libRmath-julia.dylib bd0.o dnbeta.o i1mach.o pnbinom.o qlnorm.o rgeom.o bessel_i.o dnbinom.o imax2.o pnchisq.o qlogis.o rhyper.o bessel_j.o dnchisq.o imin2.o pnf.o qnbeta.o rlnorm.o bessel_k.o dnf.o lbeta.o pnorm.o qnbinom.o rlogis.o bessel_y.o dnorm.o lgamma.o pnt.o qnchisq.o rmultinom.o beta.o dnt.o lgammacor.o polygamma.o qnf.o rnbinom.o chebyshev.o dpois.o log1p.o ppois.o qnorm.o rnchisq.o choose.o dt.o mlutils.o pt.o qnt.o rnorm.o d1mach.o dunif.o pbeta.o ptukey.o qpois.o rpois.o dbeta.o dweibull.o pbinom.o punif.o qt.o rt.o dbinom.o expm1.o pcauchy.o pweibull.o qtukey.o runif.o dcauchy.o fmax2.o pchisq.o qbeta.o qunif.o rweibull.o dchisq.o fmin2.o pexp.o qbinom.o qweibull.o dexp.o fprec.o pf.o qcauchy.o rbeta.o sign.o df.o fround.o pgamma.o qchisq.o rbinom.o signrank.o dgamma.o fsign.o pgeom.o qexp.o rcauchy.o dgeom.o ftrunc.o phyper.o qf.o rchisq.o stirlerr.o dhyper.o gamma.o plnorm.o qgamma.o rexp.o toms708.o dlnorm.o gamma_cody.o plogis.o qgeom.o rf.o wilcox.o dlogis.o gammalims.o pnbeta.o qhyper.o rgamma.o librandom.o randmtzig.o -L/Volumes/Julia-0.5.0 1/Julia-0.5.app/Contents/Resources/julia/lib/julia -ldSFMT
clang: error: no such file or directory: '1/Julia-0.5.app/Contents/Resources/julia/lib/julia'
make[1]: **\* [libRmath-julia.dylib] Error 1
make: **\* [all] Error 2
================================[ ERROR: Rmath ]================================

LoadError: failed process: Process(`make USE_DSFMT=1 DSFMT_includedir=/Users/ewelinaMac/.julia/v0.5/Rmath/deps/dSFMT 'DSFMT_libdir=/Volumes/Julia-0.5.0 1/Julia-0.5.app/Contents/Resources/julia/lib/julia'`, ProcessExited(2)) [2]
while loading /Users/ewelinaMac/.julia/v0.5/Rmath/deps/build.jl, in expression starting on line 39
# 

================================[ BUILD ERRORS ]================================

WARNING: Rmath had build errors.
- packages with build errors remain installed in /Users/ewelinaMac/.julia/v0.5
- build the package(s) and all dependencies with `Pkg.build("Rmath")`
- build a single package by running its `deps/build.jl` script

`

**Comment by StefanKarpinski** [comment]
Please post questions to the [julia-users](https://groups.google.com/forum/#!forum/julia-users) mailing list.

**Comment by tkelman** [comment]
Stefan, this is a totally valid bug report, except that it should be opened at https://github.com/JuliaStats/Rmath.jl. `deps/build.jl` is missing some quotes to handle paths with spaces.

**Comment by tkelman** [comment]
@shreczka click "Subscribe" over at https://github.com/JuliaStats/Rmath.jl/issues/22 to keep updated on what should be a fix for this. If you're in a hurry you can make the same change locally and test it, or wait (hopefully not more than a day or two at most) for that to be released through `Pkg.update()`, we'll let you know when that should work.

**Comment by shreczka** [comment]
Hi Tony!

Thanks for letting me know.
For now i switched to julia 0.4 where things work. I will try to move to 0.5.0 again in couple of days.
Best,
Ewelina

**Comment by tkelman** [comment]
`Pkg.update(); Pkg.build("Rmath")` should fix this now. Let us know.

**Comment by gilbaes** [comment]
Hi I still have this problem, see below:


julia> Pkg.build("Rmath")
INFO: Building Rmath
INFO: Attempting to Create directory /Users/pia/.julia/v0.5/Rmath/deps/downloads
INFO: Directory /Users/pia/.julia/v0.5/Rmath/deps/downloads already created
INFO: Downloading file https://github.com/JuliaLang/Rmath-julia/archive/v0.1.tar.gz
INFO: Done downloading file https://github.com/JuliaLang/Rmath-julia/archive/v0.1.tar.gz
INFO: Attempting to Create directory /Users/pia/.julia/v0.5/Rmath/deps/src
INFO: Directory /Users/pia/.julia/v0.5/Rmath/deps/src already created
INFO: Attempting to Create directory /Users/pia/.julia/v0.5/Rmath/deps
INFO: Directory /Users/pia/.julia/v0.5/Rmath/deps already created
INFO: Path /Users/pia/.julia/v0.5/Rmath/deps/src/Rmath-julia-0.1 already created
INFO: Attempting to Create directory /Users/pia/.julia/v0.5/Rmath/deps/usr/lib
INFO: Directory /Users/pia/.julia/v0.5/Rmath/deps/usr/lib already created
INFO: Changing Directory to /Users/pia/.julia/v0.5/Rmath/deps/src/Rmath-julia-0.1
make -C src
rm -rf libRmath-julia.dylib
gcc   -shared -o libRmath-julia.dylib bd0.o dnbeta.o i1mach.o pnbinom.o qlnorm.o rgeom.o bessel_i.o dnbinom.o imax2.o pnchisq.o qlogis.o rhyper.o bessel_j.o dnchisq.o imin2.o pnf.o qnbeta.o rlnorm.o bessel_k.o dnf.o lbeta.o pnorm.o qnbinom.o rlogis.o bessel_y.o dnorm.o lgamma.o pnt.o qnchisq.o rmultinom.o beta.o dnt.o lgammacor.o polygamma.o qnf.o rnbinom.o chebyshev.o dpois.o log1p.o ppois.o qnorm.o rnchisq.o choose.o dt.o mlutils.o pt.o qnt.o rnorm.o d1mach.o dunif.o pbeta.o ptukey.o qpois.o rpois.o dbeta.o dweibull.o pbinom.o punif.o qt.o rt.o dbinom.o expm1.o pcauchy.o pweibull.o qtukey.o runif.o dcauchy.o fmax2.o pchisq.o qbeta.o qunif.o rweibull.o dchisq.o fmin2.o pexp.o qbinom.o qweibull.o dexp.o fprec.o pf.o qcauchy.o rbeta.o sign.o df.o fround.o pgamma.o qchisq.o rbinom.o signrank.o dgamma.o fsign.o pgeom.o qexp.o rcauchy.o dgeom.o ftrunc.o phyper.o qf.o rchisq.o stirlerr.o dhyper.o gamma.o plnorm.o qgamma.o rexp.o toms708.o dlnorm.o gamma_cody.o plogis.o qgeom.o rf.o wilcox.o dlogis.o gammalims.o pnbeta.o qhyper.o rgamma.o librandom.o randmtzig.o -L/Applications/Julia-0.5 2.app/Contents/Resources/julia/lib/julia -ldSFMT
clang: error: no such file or directory: '2.app/Contents/Resources/julia/lib/julia'
make[1]: *** [libRmath-julia.dylib] Error 1
make: *** [all] Error 2
==========================================[ ERROR: Rmath ]==========================================

LoadError: failed process: Process(`make USE_DSFMT=1 DSFMT_includedir=/Users/pia/.julia/v0.5/Rmath/deps/dSFMT 'DSFMT_libdir=/Applications/Julia-0.5 2.app/Contents/Resources/julia/lib/julia'`, ProcessExited(2)) [2]
while loading /Users/pia/.julia/v0.5/Rmath/deps/build.jl, in expression starting on line 39

====================================================================================================

==========================================[ BUILD ERRORS ]==========================================

WARNING: Rmath had build errors.

 - packages with build errors remain installed in /Users/pia/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("Rmath")`
 - build a single package by running its `deps/build.jl` script

====================================================================================================

**Comment by tkelman** [comment]
what does `Pkg.status()` say?

**Comment by gilbaes** [comment]
Pkg.status("Rmath")
 - Rmath                         0.1.4

**Comment by gilbaes** [comment]
Pkg.status()
4 required packages:
 - DataFrames                    0.8.4
 - Distributions                 0.11.0
 - IJulia                        1.3.2
 - Plots                         0.9.3
28 additional packages:
 - BinDeps                       0.4.5
 - Calculus                      0.1.15
 - ColorTypes                    0.2.11
 - Colors                        0.6.9
 - Compat                        0.9.3
 - Conda                         0.3.2
 - DataArrays                    0.3.8
 - FileIO                        0.2.0
 - FixedPointNumbers             0.2.1
 - FixedSizeArrays               0.2.4
 - GZip                          0.2.20
 - Homebrew                      0.4.0
 - Iterators                     0.1.10
 - JSON                          0.8.0
 - Measures                      0.0.3
 - Nettle                        0.2.4
 - PDMats                        0.5.0
 - PlotUtils                     0.1.0
 - RecipesBase                   0.0.6
 - Reexport                      0.0.3
 - Rmath                         0.1.4
 - SHA                           0.2.1
 - Showoff                       0.0.7
 - SortingAlgorithms             0.1.0
 - StatsBase                     0.11.1
 - StatsFuns                     0.3.1
 - URIParser                     0.1.6
 - ZMQ                           0.3.4

**Comment by tkelman** [comment]
probably need to add quotes in the makefile here too then

**Comment by acheck10** [comment]
I'm having the same problem gilbaes was having. Same error and same Pkg.status.

**Comment by simonbyrne** [comment]
@tkelman is the issue with the dSFMT path?

We could merge #14, which gets rid of it?

**Comment by ppalmes** [comment]
for those with issues, try xcode-select --install
it will update the libraries which usually will fix the problem.

**Comment by simonbyrne** [comment]
Hopefully should be fixed now. Please open a new issue if it reappears.

**Comment by AnilJoshi** [comment]
What is the problem here with clang? I am getting similar error with GSL.

==================================[ ERROR: Clang ]===================================

LoadError: No useable llvm-config found
while loading /home/joshi/.julia/v0.5/Clang/deps/build.jl, in expression starting on line 64

=====================================================================================

==================================[ BUILD ERRORS ]===================================

WARNING: Clang had build errors.

 - packages with build errors remain installed in /home/joshi/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("Clang")`
 - build a single package by running its `deps/build.jl` script

=====================================================================================
INFO: Package database updated

**Comment by simonbyrne** [comment]
Can you provide more details? What's your `versioninfo()`?
